change readme.md
osdc/unblock pull request #3
Opened 2018-04-24 18:38 UTC by DamiyanVC

2018-04-24 18:41 UTC, ryzokuken commented on README.md
> +
nit: extra newline. Please remove this?

2018-04-24 18:43 UTC, ryzokuken approved these changes
Damn, pwnable.kr is blocked? It certainly didn't use to be. Good catch.

Could you please take care of the nit? I'd love to merge it then.

2018-04-24 18:43 UTC, ryzokuken commented on README.md
> +
Nit: extra newline. Please remove it?

2018-04-24 18:43 UTC, ryzokuken commented on README.md
> +- **Blocked Under**: Games
Confirmed.

2018-04-24 18:58 UTC, DamiyanVC commented on README.md
> +
done

2018-04-24 20:45 UTC, ryzokuken requested changes

2018-04-24 20:45 UTC, ryzokuken commented on README.md
> +### 4. Pwnabke.kr
It's mistyped.

2018-04-25 17:44 UTC, ryzokuken approved these changes

2018-04-25 17:45 UTC, ryzokuken commented
Thanks! Merging.

2018-04-25 17:45 UTC, merged