Update README.md
osdc/unblock pull request #7
Opened 2018-08-20 13:45 UTC by nightwarrior-xxx

2018-08-20 16:32 UTC, saranshbarua commented
@ryzokuken I think this is ready to be merged now.

2018-08-21 14:29 UTC, ryzokuken requested changes
A couple of concerns, PTAL at these and we'll get this merged. Thanks 🎉

2018-08-21 14:29 UTC, ryzokuken commented on README.md
> +- **About**:-Internet Relay Chat is an application layer protocol that facilitates communication in the form of text. The chat process works on a client/server networking model. IRC clients are compu
A couple of things:

1. Please don't paste the definition of IRC, just write a few sentences about why it's important to you (us).
2. Don't you think we should have a different space for services/non-websites.
3. Are you planning to add more services?

2018-08-28 04:48 UTC, ryzokuken commented
Closing in favor of #9.

2018-08-28 04:48 UTC, closed without merging